import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from "@/components/ThemeProvider"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className='bg-background text-black dark:text-white'>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
        >
            <section className="mx-auto max-w-3xl px-4 pt-20 sm:px-6 xl:max-w-[50rem] xl:px-8">
              <div className="flex h-screen flex-col justify-between font-sans">
                <main className="mb-auto">{children}</main>
              </div>
          </section>
        </ThemeProvider>
      </body>
    </html>
  </>
  )
}
